### ISSUE TITLE
Bug - 产品exchange同价格情况下由于refund为0.00所以无法进行交易

### ISSUE THREAD

**Issue by miketonny** [smarket-cc/old-jmart#22]
比如产品1 = $5.5.
客人来换产品2， 价格也是$5.5. 
点refund后更换完产品无法点‘refund’

**Comment by miketonny** [comment]
积分兑换也是一样的情况，比如买$5.5的产品，如果我用5500分兑换$5.5的credit，最后付款为0，pos不让交易目前

**Comment by lihaooo** [comment]
了解，这个看怎么处理比较好，允许0元的交易？

**Comment by miketonny** [comment]
允许吧，小票打印出来得确认下

**Comment by lihaooo** [comment]
好的，这个我今天会处理好

**Comment by lihaooo** [comment]
@miketonny 
已部署，请通知更新pos
1. 如果结算金额为0，只能用cash结算，别的方式无法正确创建订单
2. 修复了一个UI bug，偶尔在逻辑错误时会出现cash refund之类的空框体无法消除

**Comment by lihaooo** [comment]
似乎UI bug的调整影响了card transaction的id流，导致出现id无法match的情况，先rollback这个部分

**Comment by lihaooo** [comment]
@miketonny 
已经部署，请通知更新pos，此issue先放在QA留观一周
